<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs-realtime-final.proto

namespace Transit_realtime\TripUpdate\StopTimeUpdate\StopTimeProperties;

use UnexpectedValueException;

/**
 * Protobuf type <code>transit_realtime.TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType</code>
 */
class DropOffPickupType
{
    /**
     * Regularly scheduled pickup/dropoff.
     *
     * Generated from protobuf enum <code>REGULAR = 0;</code>
     */
    const REGULAR = 0;
    /**
     * No pickup/dropoff available
     *
     * Generated from protobuf enum <code>NONE = 1;</code>
     */
    const NONE = 1;
    /**
     * Must phone agency to arrange pickup/dropoff.
     *
     * Generated from protobuf enum <code>PHONE_AGENCY = 2;</code>
     */
    const PHONE_AGENCY = 2;
    /**
     * Must coordinate with driver to arrange pickup/dropoff.
     *
     * Generated from protobuf enum <code>COORDINATE_WITH_DRIVER = 3;</code>
     */
    const COORDINATE_WITH_DRIVER = 3;

    private static $valueToName = [
        self::REGULAR => 'REGULAR',
        self::NONE => 'NONE',
        self::PHONE_AGENCY => 'PHONE_AGENCY',
        self::COORDINATE_WITH_DRIVER => 'COORDINATE_WITH_DRIVER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(DropOffPickupType::class, \Transit_realtime\TripUpdate_StopTimeUpdate_StopTimeProperties_DropOffPickupType::class);

