<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs-realtime-final.proto

namespace Transit_realtime\TripUpdate\StopTimeUpdate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Provides the updated values for the stop time.
 * NOTE: This message is still experimental, and subject to change. It may be formally adopted in the future.
 *
 * Generated from protobuf message <code>transit_realtime.TripUpdate.StopTimeUpdate.StopTimeProperties</code>
 */
class StopTimeProperties extends \Google\Protobuf\Internal\Message
{
    /**
     * Supports real-time stop assignments. Refers to a stop_id defined in the GTFS stops.txt.
     * The new assigned_stop_id should not result in a significantly different trip experience for the end user than
     * the stop_id defined in GTFS stop_times.txt. In other words, the end user should not view this new stop_id as an
     * "unusual change" if the new stop was presented within an app without any additional context.
     * For example, this field is intended to be used for platform assignments by using a stop_id that belongs to the
     * same station as the stop originally defined in GTFS stop_times.txt.
     * To assign a stop without providing any real-time arrival or departure predictions, populate this field and set
     * StopTimeUpdate.schedule_relationship = NO_DATA.
     * If this field is populated, it is preferred to omit `StopTimeUpdate.stop_id` and use only `StopTimeUpdate.stop_sequence`. If
     * `StopTimeProperties.assigned_stop_id` and `StopTimeUpdate.stop_id` are populated, `StopTimeUpdate.stop_id` must match `assigned_stop_id`.
     * Platform assignments should be reflected in other GTFS-realtime fields as well
     * (e.g., `VehiclePosition.stop_id`).
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string assigned_stop_id = 1;</code>
     */
    protected $assigned_stop_id = null;
    /**
     * The updated headsign of the vehicle at the stop.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string stop_headsign = 2;</code>
     */
    protected $stop_headsign = null;
    /**
     * The updated pickup of the vehicle at the stop.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType pickup_type = 3;</code>
     */
    protected $pickup_type = null;
    /**
     * The updated drop off of the vehicle at the stop.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType drop_off_type = 4;</code>
     */
    protected $drop_off_type = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $assigned_stop_id
     *           Supports real-time stop assignments. Refers to a stop_id defined in the GTFS stops.txt.
     *           The new assigned_stop_id should not result in a significantly different trip experience for the end user than
     *           the stop_id defined in GTFS stop_times.txt. In other words, the end user should not view this new stop_id as an
     *           "unusual change" if the new stop was presented within an app without any additional context.
     *           For example, this field is intended to be used for platform assignments by using a stop_id that belongs to the
     *           same station as the stop originally defined in GTFS stop_times.txt.
     *           To assign a stop without providing any real-time arrival or departure predictions, populate this field and set
     *           StopTimeUpdate.schedule_relationship = NO_DATA.
     *           If this field is populated, it is preferred to omit `StopTimeUpdate.stop_id` and use only `StopTimeUpdate.stop_sequence`. If
     *           `StopTimeProperties.assigned_stop_id` and `StopTimeUpdate.stop_id` are populated, `StopTimeUpdate.stop_id` must match `assigned_stop_id`.
     *           Platform assignments should be reflected in other GTFS-realtime fields as well
     *           (e.g., `VehiclePosition.stop_id`).
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *     @type string $stop_headsign
     *           The updated headsign of the vehicle at the stop.
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *     @type int $pickup_type
     *           The updated pickup of the vehicle at the stop.
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *     @type int $drop_off_type
     *           The updated drop off of the vehicle at the stop.
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GtfsRealtimeFinal::initOnce();
        parent::__construct($data);
    }

    /**
     * Supports real-time stop assignments. Refers to a stop_id defined in the GTFS stops.txt.
     * The new assigned_stop_id should not result in a significantly different trip experience for the end user than
     * the stop_id defined in GTFS stop_times.txt. In other words, the end user should not view this new stop_id as an
     * "unusual change" if the new stop was presented within an app without any additional context.
     * For example, this field is intended to be used for platform assignments by using a stop_id that belongs to the
     * same station as the stop originally defined in GTFS stop_times.txt.
     * To assign a stop without providing any real-time arrival or departure predictions, populate this field and set
     * StopTimeUpdate.schedule_relationship = NO_DATA.
     * If this field is populated, it is preferred to omit `StopTimeUpdate.stop_id` and use only `StopTimeUpdate.stop_sequence`. If
     * `StopTimeProperties.assigned_stop_id` and `StopTimeUpdate.stop_id` are populated, `StopTimeUpdate.stop_id` must match `assigned_stop_id`.
     * Platform assignments should be reflected in other GTFS-realtime fields as well
     * (e.g., `VehiclePosition.stop_id`).
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string assigned_stop_id = 1;</code>
     * @return string
     */
    public function getAssignedStopId()
    {
        return isset($this->assigned_stop_id) ? $this->assigned_stop_id : '';
    }

    public function hasAssignedStopId()
    {
        return isset($this->assigned_stop_id);
    }

    public function clearAssignedStopId()
    {
        unset($this->assigned_stop_id);
    }

    /**
     * Supports real-time stop assignments. Refers to a stop_id defined in the GTFS stops.txt.
     * The new assigned_stop_id should not result in a significantly different trip experience for the end user than
     * the stop_id defined in GTFS stop_times.txt. In other words, the end user should not view this new stop_id as an
     * "unusual change" if the new stop was presented within an app without any additional context.
     * For example, this field is intended to be used for platform assignments by using a stop_id that belongs to the
     * same station as the stop originally defined in GTFS stop_times.txt.
     * To assign a stop without providing any real-time arrival or departure predictions, populate this field and set
     * StopTimeUpdate.schedule_relationship = NO_DATA.
     * If this field is populated, it is preferred to omit `StopTimeUpdate.stop_id` and use only `StopTimeUpdate.stop_sequence`. If
     * `StopTimeProperties.assigned_stop_id` and `StopTimeUpdate.stop_id` are populated, `StopTimeUpdate.stop_id` must match `assigned_stop_id`.
     * Platform assignments should be reflected in other GTFS-realtime fields as well
     * (e.g., `VehiclePosition.stop_id`).
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string assigned_stop_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAssignedStopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->assigned_stop_id = $var;

        return $this;
    }

    /**
     * The updated headsign of the vehicle at the stop.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string stop_headsign = 2;</code>
     * @return string
     */
    public function getStopHeadsign()
    {
        return isset($this->stop_headsign) ? $this->stop_headsign : '';
    }

    public function hasStopHeadsign()
    {
        return isset($this->stop_headsign);
    }

    public function clearStopHeadsign()
    {
        unset($this->stop_headsign);
    }

    /**
     * The updated headsign of the vehicle at the stop.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string stop_headsign = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStopHeadsign($var)
    {
        GPBUtil::checkString($var, True);
        $this->stop_headsign = $var;

        return $this;
    }

    /**
     * The updated pickup of the vehicle at the stop.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType pickup_type = 3;</code>
     * @return int
     */
    public function getPickupType()
    {
        return isset($this->pickup_type) ? $this->pickup_type : 0;
    }

    public function hasPickupType()
    {
        return isset($this->pickup_type);
    }

    public function clearPickupType()
    {
        unset($this->pickup_type);
    }

    /**
     * The updated pickup of the vehicle at the stop.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType pickup_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPickupType($var)
    {
        GPBUtil::checkEnum($var, \Transit_realtime\TripUpdate\StopTimeUpdate\StopTimeProperties\DropOffPickupType::class);
        $this->pickup_type = $var;

        return $this;
    }

    /**
     * The updated drop off of the vehicle at the stop.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType drop_off_type = 4;</code>
     * @return int
     */
    public function getDropOffType()
    {
        return isset($this->drop_off_type) ? $this->drop_off_type : 0;
    }

    public function hasDropOffType()
    {
        return isset($this->drop_off_type);
    }

    public function clearDropOffType()
    {
        unset($this->drop_off_type);
    }

    /**
     * The updated drop off of the vehicle at the stop.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeUpdate.StopTimeProperties.DropOffPickupType drop_off_type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDropOffType($var)
    {
        GPBUtil::checkEnum($var, \Transit_realtime\TripUpdate\StopTimeUpdate\StopTimeProperties\DropOffPickupType::class);
        $this->drop_off_type = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(StopTimeProperties::class, \Transit_realtime\TripUpdate_StopTimeUpdate_StopTimeProperties::class);

