<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs-realtime-final.proto

namespace Transit_realtime\TripDescriptor;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transit_realtime.TripDescriptor.ModifiedTripSelector</code>
 */
class ModifiedTripSelector extends \Google\Protobuf\Internal\Message
{
    /**
     * The 'id' from the FeedEntity in which the contained TripModifications object affects this trip.
     *
     * Generated from protobuf field <code>optional string modifications_id = 1;</code>
     */
    protected $modifications_id = null;
    /**
     * The trip_id from the GTFS feed that is modified by the modifications_id
     *
     * Generated from protobuf field <code>optional string affected_trip_id = 2;</code>
     */
    protected $affected_trip_id = null;
    /**
     * The initially scheduled start time of this trip instance, applied to the frequency based modified trip. Same definition as start_time in TripDescriptor.
     *
     * Generated from protobuf field <code>optional string start_time = 3;</code>
     */
    protected $start_time = null;
    /**
     * The start date of this trip instance in YYYYMMDD format, applied to the modified trip. Same definition as start_date in TripDescriptor.
     *
     * Generated from protobuf field <code>optional string start_date = 4;</code>
     */
    protected $start_date = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $modifications_id
     *           The 'id' from the FeedEntity in which the contained TripModifications object affects this trip.
     *     @type string $affected_trip_id
     *           The trip_id from the GTFS feed that is modified by the modifications_id
     *     @type string $start_time
     *           The initially scheduled start time of this trip instance, applied to the frequency based modified trip. Same definition as start_time in TripDescriptor.
     *     @type string $start_date
     *           The start date of this trip instance in YYYYMMDD format, applied to the modified trip. Same definition as start_date in TripDescriptor.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GtfsRealtimeFinal::initOnce();
        parent::__construct($data);
    }

    /**
     * The 'id' from the FeedEntity in which the contained TripModifications object affects this trip.
     *
     * Generated from protobuf field <code>optional string modifications_id = 1;</code>
     * @return string
     */
    public function getModificationsId()
    {
        return isset($this->modifications_id) ? $this->modifications_id : '';
    }

    public function hasModificationsId()
    {
        return isset($this->modifications_id);
    }

    public function clearModificationsId()
    {
        unset($this->modifications_id);
    }

    /**
     * The 'id' from the FeedEntity in which the contained TripModifications object affects this trip.
     *
     * Generated from protobuf field <code>optional string modifications_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setModificationsId($var)
    {
        GPBUtil::checkString($var, True);
        $this->modifications_id = $var;

        return $this;
    }

    /**
     * The trip_id from the GTFS feed that is modified by the modifications_id
     *
     * Generated from protobuf field <code>optional string affected_trip_id = 2;</code>
     * @return string
     */
    public function getAffectedTripId()
    {
        return isset($this->affected_trip_id) ? $this->affected_trip_id : '';
    }

    public function hasAffectedTripId()
    {
        return isset($this->affected_trip_id);
    }

    public function clearAffectedTripId()
    {
        unset($this->affected_trip_id);
    }

    /**
     * The trip_id from the GTFS feed that is modified by the modifications_id
     *
     * Generated from protobuf field <code>optional string affected_trip_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAffectedTripId($var)
    {
        GPBUtil::checkString($var, True);
        $this->affected_trip_id = $var;

        return $this;
    }

    /**
     * The initially scheduled start time of this trip instance, applied to the frequency based modified trip. Same definition as start_time in TripDescriptor.
     *
     * Generated from protobuf field <code>optional string start_time = 3;</code>
     * @return string
     */
    public function getStartTime()
    {
        return isset($this->start_time) ? $this->start_time : '';
    }

    public function hasStartTime()
    {
        return isset($this->start_time);
    }

    public function clearStartTime()
    {
        unset($this->start_time);
    }

    /**
     * The initially scheduled start time of this trip instance, applied to the frequency based modified trip. Same definition as start_time in TripDescriptor.
     *
     * Generated from protobuf field <code>optional string start_time = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_time = $var;

        return $this;
    }

    /**
     * The start date of this trip instance in YYYYMMDD format, applied to the modified trip. Same definition as start_date in TripDescriptor.
     *
     * Generated from protobuf field <code>optional string start_date = 4;</code>
     * @return string
     */
    public function getStartDate()
    {
        return isset($this->start_date) ? $this->start_date : '';
    }

    public function hasStartDate()
    {
        return isset($this->start_date);
    }

    public function clearStartDate()
    {
        unset($this->start_date);
    }

    /**
     * The start date of this trip instance in YYYYMMDD format, applied to the modified trip. Same definition as start_date in TripDescriptor.
     *
     * Generated from protobuf field <code>optional string start_date = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_date = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ModifiedTripSelector::class, \Transit_realtime\TripDescriptor_ModifiedTripSelector::class);

