<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs-realtime-final.proto

namespace Transit_realtime\TripUpdate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Timing information for a single predicted event (either arrival or
 * departure).
 * Timing consists of delay and/or estimated time, and uncertainty.
 * - delay should be used when the prediction is given relative to some
 *   existing schedule in GTFS.
 * - time should be given whether there is a predicted schedule or not. If
 *   both time and delay are specified, time will take precedence
 *   (although normally, time, if given for a scheduled trip, should be
 *   equal to scheduled time in GTFS + delay).
 * Uncertainty applies equally to both time and delay.
 * The uncertainty roughly specifies the expected error in true delay (but
 * note, we don't yet define its precise statistical meaning). It's possible
 * for the uncertainty to be 0, for example for trains that are driven under
 * computer timing control.
 *
 * Generated from protobuf message <code>transit_realtime.TripUpdate.StopTimeEvent</code>
 */
class StopTimeEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Delay (in seconds) can be positive (meaning that the vehicle is late) or
     * negative (meaning that the vehicle is ahead of schedule). Delay of 0
     * means that the vehicle is exactly on time.
     *
     * Generated from protobuf field <code>optional int32 delay = 1;</code>
     */
    protected $delay = null;
    /**
     * Event as absolute time.
     * In Unix time (i.e., number of seconds since January 1st 1970 00:00:00
     * UTC).
     *
     * Generated from protobuf field <code>optional int64 time = 2;</code>
     */
    protected $time = null;
    /**
     * If uncertainty is omitted, it is interpreted as unknown.
     * If the prediction is unknown or too uncertain, the delay (or time) field
     * should be empty. In such case, the uncertainty field is ignored.
     * To specify a completely certain prediction, set its uncertainty to 0.
     *
     * Generated from protobuf field <code>optional int32 uncertainty = 3;</code>
     */
    protected $uncertainty = null;
    /**
     * Scheduled time for a NEW, REPLACEMENT, or DUPLICATED trip.
     * In Unix time (i.e., number of seconds since January 1st 1970 00:00:00
     * UTC).
     * Optional if TripUpdate.schedule_relationship is NEW, REPLACEMENT or DUPLICATED, forbidden otherwise.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional int64 scheduled_time = 4;</code>
     */
    protected $scheduled_time = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $delay
     *           Delay (in seconds) can be positive (meaning that the vehicle is late) or
     *           negative (meaning that the vehicle is ahead of schedule). Delay of 0
     *           means that the vehicle is exactly on time.
     *     @type int|string $time
     *           Event as absolute time.
     *           In Unix time (i.e., number of seconds since January 1st 1970 00:00:00
     *           UTC).
     *     @type int $uncertainty
     *           If uncertainty is omitted, it is interpreted as unknown.
     *           If the prediction is unknown or too uncertain, the delay (or time) field
     *           should be empty. In such case, the uncertainty field is ignored.
     *           To specify a completely certain prediction, set its uncertainty to 0.
     *     @type int|string $scheduled_time
     *           Scheduled time for a NEW, REPLACEMENT, or DUPLICATED trip.
     *           In Unix time (i.e., number of seconds since January 1st 1970 00:00:00
     *           UTC).
     *           Optional if TripUpdate.schedule_relationship is NEW, REPLACEMENT or DUPLICATED, forbidden otherwise.
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GtfsRealtimeFinal::initOnce();
        parent::__construct($data);
    }

    /**
     * Delay (in seconds) can be positive (meaning that the vehicle is late) or
     * negative (meaning that the vehicle is ahead of schedule). Delay of 0
     * means that the vehicle is exactly on time.
     *
     * Generated from protobuf field <code>optional int32 delay = 1;</code>
     * @return int
     */
    public function getDelay()
    {
        return isset($this->delay) ? $this->delay : 0;
    }

    public function hasDelay()
    {
        return isset($this->delay);
    }

    public function clearDelay()
    {
        unset($this->delay);
    }

    /**
     * Delay (in seconds) can be positive (meaning that the vehicle is late) or
     * negative (meaning that the vehicle is ahead of schedule). Delay of 0
     * means that the vehicle is exactly on time.
     *
     * Generated from protobuf field <code>optional int32 delay = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDelay($var)
    {
        GPBUtil::checkInt32($var);
        $this->delay = $var;

        return $this;
    }

    /**
     * Event as absolute time.
     * In Unix time (i.e., number of seconds since January 1st 1970 00:00:00
     * UTC).
     *
     * Generated from protobuf field <code>optional int64 time = 2;</code>
     * @return int|string
     */
    public function getTime()
    {
        return isset($this->time) ? $this->time : 0;
    }

    public function hasTime()
    {
        return isset($this->time);
    }

    public function clearTime()
    {
        unset($this->time);
    }

    /**
     * Event as absolute time.
     * In Unix time (i.e., number of seconds since January 1st 1970 00:00:00
     * UTC).
     *
     * Generated from protobuf field <code>optional int64 time = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;

        return $this;
    }

    /**
     * If uncertainty is omitted, it is interpreted as unknown.
     * If the prediction is unknown or too uncertain, the delay (or time) field
     * should be empty. In such case, the uncertainty field is ignored.
     * To specify a completely certain prediction, set its uncertainty to 0.
     *
     * Generated from protobuf field <code>optional int32 uncertainty = 3;</code>
     * @return int
     */
    public function getUncertainty()
    {
        return isset($this->uncertainty) ? $this->uncertainty : 0;
    }

    public function hasUncertainty()
    {
        return isset($this->uncertainty);
    }

    public function clearUncertainty()
    {
        unset($this->uncertainty);
    }

    /**
     * If uncertainty is omitted, it is interpreted as unknown.
     * If the prediction is unknown or too uncertain, the delay (or time) field
     * should be empty. In such case, the uncertainty field is ignored.
     * To specify a completely certain prediction, set its uncertainty to 0.
     *
     * Generated from protobuf field <code>optional int32 uncertainty = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUncertainty($var)
    {
        GPBUtil::checkInt32($var);
        $this->uncertainty = $var;

        return $this;
    }

    /**
     * Scheduled time for a NEW, REPLACEMENT, or DUPLICATED trip.
     * In Unix time (i.e., number of seconds since January 1st 1970 00:00:00
     * UTC).
     * Optional if TripUpdate.schedule_relationship is NEW, REPLACEMENT or DUPLICATED, forbidden otherwise.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional int64 scheduled_time = 4;</code>
     * @return int|string
     */
    public function getScheduledTime()
    {
        return isset($this->scheduled_time) ? $this->scheduled_time : 0;
    }

    public function hasScheduledTime()
    {
        return isset($this->scheduled_time);
    }

    public function clearScheduledTime()
    {
        unset($this->scheduled_time);
    }

    /**
     * Scheduled time for a NEW, REPLACEMENT, or DUPLICATED trip.
     * In Unix time (i.e., number of seconds since January 1st 1970 00:00:00
     * UTC).
     * Optional if TripUpdate.schedule_relationship is NEW, REPLACEMENT or DUPLICATED, forbidden otherwise.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional int64 scheduled_time = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setScheduledTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->scheduled_time = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(StopTimeEvent::class, \Transit_realtime\TripUpdate_StopTimeEvent::class);

