<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs-realtime-final.proto

namespace Transit_realtime\TripUpdate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Realtime update for arrival and/or departure events for a given stop on a
 * trip. Updates can be supplied for both past and future events.
 * The producer is allowed, although not required, to drop past events.
 *
 * Generated from protobuf message <code>transit_realtime.TripUpdate.StopTimeUpdate</code>
 */
class StopTimeUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Must be the same as in stop_times.txt in the corresponding GTFS feed.
     *
     * Generated from protobuf field <code>optional uint32 stop_sequence = 1;</code>
     */
    protected $stop_sequence = null;
    /**
     * Must be the same as in stops.txt in the corresponding GTFS feed.
     *
     * Generated from protobuf field <code>optional string stop_id = 4;</code>
     */
    protected $stop_id = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeEvent arrival = 2;</code>
     */
    protected $arrival = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeEvent departure = 3;</code>
     */
    protected $departure = null;
    /**
     * Expected occupancy after departure from the given stop.
     * Should be provided only for future stops.
     * In order to provide departure_occupancy_status without either arrival or
     * departure StopTimeEvents, ScheduleRelationship should be set to NO_DATA. 
     *
     * Generated from protobuf field <code>optional .transit_realtime.VehiclePosition.OccupancyStatus departure_occupancy_status = 7;</code>
     */
    protected $departure_occupancy_status = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeUpdate.ScheduleRelationship schedule_relationship = 5;</code>
     */
    protected $schedule_relationship = null;
    /**
     * Realtime updates for certain properties defined within GTFS stop_times.txt
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeUpdate.StopTimeProperties stop_time_properties = 6;</code>
     */
    protected $stop_time_properties = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $stop_sequence
     *           Must be the same as in stop_times.txt in the corresponding GTFS feed.
     *     @type string $stop_id
     *           Must be the same as in stops.txt in the corresponding GTFS feed.
     *     @type \Transit_realtime\TripUpdate\StopTimeEvent $arrival
     *     @type \Transit_realtime\TripUpdate\StopTimeEvent $departure
     *     @type int $departure_occupancy_status
     *           Expected occupancy after departure from the given stop.
     *           Should be provided only for future stops.
     *           In order to provide departure_occupancy_status without either arrival or
     *           departure StopTimeEvents, ScheduleRelationship should be set to NO_DATA. 
     *     @type int $schedule_relationship
     *     @type \Transit_realtime\TripUpdate\StopTimeUpdate\StopTimeProperties $stop_time_properties
     *           Realtime updates for certain properties defined within GTFS stop_times.txt
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GtfsRealtimeFinal::initOnce();
        parent::__construct($data);
    }

    /**
     * Must be the same as in stop_times.txt in the corresponding GTFS feed.
     *
     * Generated from protobuf field <code>optional uint32 stop_sequence = 1;</code>
     * @return int
     */
    public function getStopSequence()
    {
        return isset($this->stop_sequence) ? $this->stop_sequence : 0;
    }

    public function hasStopSequence()
    {
        return isset($this->stop_sequence);
    }

    public function clearStopSequence()
    {
        unset($this->stop_sequence);
    }

    /**
     * Must be the same as in stop_times.txt in the corresponding GTFS feed.
     *
     * Generated from protobuf field <code>optional uint32 stop_sequence = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStopSequence($var)
    {
        GPBUtil::checkUint32($var);
        $this->stop_sequence = $var;

        return $this;
    }

    /**
     * Must be the same as in stops.txt in the corresponding GTFS feed.
     *
     * Generated from protobuf field <code>optional string stop_id = 4;</code>
     * @return string
     */
    public function getStopId()
    {
        return isset($this->stop_id) ? $this->stop_id : '';
    }

    public function hasStopId()
    {
        return isset($this->stop_id);
    }

    public function clearStopId()
    {
        unset($this->stop_id);
    }

    /**
     * Must be the same as in stops.txt in the corresponding GTFS feed.
     *
     * Generated from protobuf field <code>optional string stop_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeEvent arrival = 2;</code>
     * @return \Transit_realtime\TripUpdate\StopTimeEvent|null
     */
    public function getArrival()
    {
        return $this->arrival;
    }

    public function hasArrival()
    {
        return isset($this->arrival);
    }

    public function clearArrival()
    {
        unset($this->arrival);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeEvent arrival = 2;</code>
     * @param \Transit_realtime\TripUpdate\StopTimeEvent $var
     * @return $this
     */
    public function setArrival($var)
    {
        GPBUtil::checkMessage($var, \Transit_realtime\TripUpdate\StopTimeEvent::class);
        $this->arrival = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeEvent departure = 3;</code>
     * @return \Transit_realtime\TripUpdate\StopTimeEvent|null
     */
    public function getDeparture()
    {
        return $this->departure;
    }

    public function hasDeparture()
    {
        return isset($this->departure);
    }

    public function clearDeparture()
    {
        unset($this->departure);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeEvent departure = 3;</code>
     * @param \Transit_realtime\TripUpdate\StopTimeEvent $var
     * @return $this
     */
    public function setDeparture($var)
    {
        GPBUtil::checkMessage($var, \Transit_realtime\TripUpdate\StopTimeEvent::class);
        $this->departure = $var;

        return $this;
    }

    /**
     * Expected occupancy after departure from the given stop.
     * Should be provided only for future stops.
     * In order to provide departure_occupancy_status without either arrival or
     * departure StopTimeEvents, ScheduleRelationship should be set to NO_DATA. 
     *
     * Generated from protobuf field <code>optional .transit_realtime.VehiclePosition.OccupancyStatus departure_occupancy_status = 7;</code>
     * @return int
     */
    public function getDepartureOccupancyStatus()
    {
        return isset($this->departure_occupancy_status) ? $this->departure_occupancy_status : 0;
    }

    public function hasDepartureOccupancyStatus()
    {
        return isset($this->departure_occupancy_status);
    }

    public function clearDepartureOccupancyStatus()
    {
        unset($this->departure_occupancy_status);
    }

    /**
     * Expected occupancy after departure from the given stop.
     * Should be provided only for future stops.
     * In order to provide departure_occupancy_status without either arrival or
     * departure StopTimeEvents, ScheduleRelationship should be set to NO_DATA. 
     *
     * Generated from protobuf field <code>optional .transit_realtime.VehiclePosition.OccupancyStatus departure_occupancy_status = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setDepartureOccupancyStatus($var)
    {
        GPBUtil::checkEnum($var, \Transit_realtime\VehiclePosition\OccupancyStatus::class);
        $this->departure_occupancy_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeUpdate.ScheduleRelationship schedule_relationship = 5;</code>
     * @return int
     */
    public function getScheduleRelationship()
    {
        return isset($this->schedule_relationship) ? $this->schedule_relationship : 0;
    }

    public function hasScheduleRelationship()
    {
        return isset($this->schedule_relationship);
    }

    public function clearScheduleRelationship()
    {
        unset($this->schedule_relationship);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeUpdate.ScheduleRelationship schedule_relationship = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setScheduleRelationship($var)
    {
        GPBUtil::checkEnum($var, \Transit_realtime\TripUpdate\StopTimeUpdate\ScheduleRelationship::class);
        $this->schedule_relationship = $var;

        return $this;
    }

    /**
     * Realtime updates for certain properties defined within GTFS stop_times.txt
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeUpdate.StopTimeProperties stop_time_properties = 6;</code>
     * @return \Transit_realtime\TripUpdate\StopTimeUpdate\StopTimeProperties|null
     */
    public function getStopTimeProperties()
    {
        return $this->stop_time_properties;
    }

    public function hasStopTimeProperties()
    {
        return isset($this->stop_time_properties);
    }

    public function clearStopTimeProperties()
    {
        unset($this->stop_time_properties);
    }

    /**
     * Realtime updates for certain properties defined within GTFS stop_times.txt
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional .transit_realtime.TripUpdate.StopTimeUpdate.StopTimeProperties stop_time_properties = 6;</code>
     * @param \Transit_realtime\TripUpdate\StopTimeUpdate\StopTimeProperties $var
     * @return $this
     */
    public function setStopTimeProperties($var)
    {
        GPBUtil::checkMessage($var, \Transit_realtime\TripUpdate\StopTimeUpdate\StopTimeProperties::class);
        $this->stop_time_properties = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(StopTimeUpdate::class, \Transit_realtime\TripUpdate_StopTimeUpdate::class);

