<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs-realtime-final.proto

namespace Transit_realtime\TripUpdate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Defines updated properties of the trip, such as a new shape_id when there is a detour. Or defines the
 * trip_id, start_date, and start_time of a DUPLICATED trip. 
 * NOTE: This message is still experimental, and subject to change. It may be formally adopted in the future.
 *
 * Generated from protobuf message <code>transit_realtime.TripUpdate.TripProperties</code>
 */
class TripProperties extends \Google\Protobuf\Internal\Message
{
    /**
     * Defines the identifier of a new trip that is a duplicate of an existing trip defined in (CSV) GTFS trips.txt
     * but will start at a different service date and/or time (defined using the TripProperties.start_date and
     * TripProperties.start_time fields). See definition of trips.trip_id in (CSV) GTFS. Its value must be different
     * than the ones used in the (CSV) GTFS. Required if schedule_relationship=DUPLICATED, otherwise this field must not
     * be populated and will be ignored by consumers.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string trip_id = 1;</code>
     */
    protected $trip_id = null;
    /**
     * Service date on which the DUPLICATED trip will be run, in YYYYMMDD format. Required if
     * schedule_relationship=DUPLICATED, otherwise this field must not be populated and will be ignored by consumers.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string start_date = 2;</code>
     */
    protected $start_date = null;
    /**
     * Defines the departure start time of the trip when it’s duplicated. See definition of stop_times.departure_time
     * in (CSV) GTFS. Scheduled arrival and departure times for the duplicated trip are calculated based on the offset
     * between the original trip departure_time and this field. For example, if a GTFS trip has stop A with a
     * departure_time of 10:00:00 and stop B with departure_time of 10:01:00, and this field is populated with the value
     * of 10:30:00, stop B on the duplicated trip will have a scheduled departure_time of 10:31:00. Real-time prediction
     * delay values are applied to this calculated schedule time to determine the predicted time. For example, if a
     * departure delay of 30 is provided for stop B, then the predicted departure time is 10:31:30. Real-time
     * prediction time values do not have any offset applied to them and indicate the predicted time as provided.
     * For example, if a departure time representing 10:31:30 is provided for stop B, then the predicted departure time
     * is 10:31:30. This field is optional if schedule_relationship is DUPLICATED, otherwise this field must not be
     * populated and will be ignored by consumers.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string start_time = 3;</code>
     */
    protected $start_time = null;
    /**
     * Specifies the identifier of the shape of the vehicle travel path when the trip shape differs from the shape specified in (CSV) GTFS
     * or to specify it in real-time when it's not provided by (CSV) GTFS, such as a vehicle that takes differing paths based on rider demand. See definition of trips.shape_id in (CSV) GTFS.
     * If a shape is neither defined in (CSV) GTFS nor in real-time, the shape is considered unknown. This field can refer to a shape defined in the (CSV) GTFS in shapes.txt or a `Shape` in the same (protobuf) real-time feed. 
     * The order of stops (stop sequences) for this trip must remain the same as (CSV) GTFS. 
     * If it refers to a `Shape` entity in the same real-time feed, the value of this field should be the one of the `shape_id` inside the entity, and _not_ the `id` of `FeedEntity`.
     * Stops that are a part of the original trip but will no longer be made, such as when a detour occurs, should be marked as schedule_relationship=SKIPPED or more details can be provided via a `TripModifications` message.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future. 
     *
     * Generated from protobuf field <code>optional string shape_id = 4;</code>
     */
    protected $shape_id = null;
    /**
     * Specifies the headsign for this trip when it differs from the original.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string trip_headsign = 5;</code>
     */
    protected $trip_headsign = null;
    /**
     * Specifies the name for this trip when it differs from the original.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string trip_short_name = 6;</code>
     */
    protected $trip_short_name = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $trip_id
     *           Defines the identifier of a new trip that is a duplicate of an existing trip defined in (CSV) GTFS trips.txt
     *           but will start at a different service date and/or time (defined using the TripProperties.start_date and
     *           TripProperties.start_time fields). See definition of trips.trip_id in (CSV) GTFS. Its value must be different
     *           than the ones used in the (CSV) GTFS. Required if schedule_relationship=DUPLICATED, otherwise this field must not
     *           be populated and will be ignored by consumers.
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *     @type string $start_date
     *           Service date on which the DUPLICATED trip will be run, in YYYYMMDD format. Required if
     *           schedule_relationship=DUPLICATED, otherwise this field must not be populated and will be ignored by consumers.
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *     @type string $start_time
     *           Defines the departure start time of the trip when it’s duplicated. See definition of stop_times.departure_time
     *           in (CSV) GTFS. Scheduled arrival and departure times for the duplicated trip are calculated based on the offset
     *           between the original trip departure_time and this field. For example, if a GTFS trip has stop A with a
     *           departure_time of 10:00:00 and stop B with departure_time of 10:01:00, and this field is populated with the value
     *           of 10:30:00, stop B on the duplicated trip will have a scheduled departure_time of 10:31:00. Real-time prediction
     *           delay values are applied to this calculated schedule time to determine the predicted time. For example, if a
     *           departure delay of 30 is provided for stop B, then the predicted departure time is 10:31:30. Real-time
     *           prediction time values do not have any offset applied to them and indicate the predicted time as provided.
     *           For example, if a departure time representing 10:31:30 is provided for stop B, then the predicted departure time
     *           is 10:31:30. This field is optional if schedule_relationship is DUPLICATED, otherwise this field must not be
     *           populated and will be ignored by consumers.
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *     @type string $shape_id
     *           Specifies the identifier of the shape of the vehicle travel path when the trip shape differs from the shape specified in (CSV) GTFS
     *           or to specify it in real-time when it's not provided by (CSV) GTFS, such as a vehicle that takes differing paths based on rider demand. See definition of trips.shape_id in (CSV) GTFS.
     *           If a shape is neither defined in (CSV) GTFS nor in real-time, the shape is considered unknown. This field can refer to a shape defined in the (CSV) GTFS in shapes.txt or a `Shape` in the same (protobuf) real-time feed. 
     *           The order of stops (stop sequences) for this trip must remain the same as (CSV) GTFS. 
     *           If it refers to a `Shape` entity in the same real-time feed, the value of this field should be the one of the `shape_id` inside the entity, and _not_ the `id` of `FeedEntity`.
     *           Stops that are a part of the original trip but will no longer be made, such as when a detour occurs, should be marked as schedule_relationship=SKIPPED or more details can be provided via a `TripModifications` message.
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future. 
     *     @type string $trip_headsign
     *           Specifies the headsign for this trip when it differs from the original.
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *     @type string $trip_short_name
     *           Specifies the name for this trip when it differs from the original.
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GtfsRealtimeFinal::initOnce();
        parent::__construct($data);
    }

    /**
     * Defines the identifier of a new trip that is a duplicate of an existing trip defined in (CSV) GTFS trips.txt
     * but will start at a different service date and/or time (defined using the TripProperties.start_date and
     * TripProperties.start_time fields). See definition of trips.trip_id in (CSV) GTFS. Its value must be different
     * than the ones used in the (CSV) GTFS. Required if schedule_relationship=DUPLICATED, otherwise this field must not
     * be populated and will be ignored by consumers.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string trip_id = 1;</code>
     * @return string
     */
    public function getTripId()
    {
        return isset($this->trip_id) ? $this->trip_id : '';
    }

    public function hasTripId()
    {
        return isset($this->trip_id);
    }

    public function clearTripId()
    {
        unset($this->trip_id);
    }

    /**
     * Defines the identifier of a new trip that is a duplicate of an existing trip defined in (CSV) GTFS trips.txt
     * but will start at a different service date and/or time (defined using the TripProperties.start_date and
     * TripProperties.start_time fields). See definition of trips.trip_id in (CSV) GTFS. Its value must be different
     * than the ones used in the (CSV) GTFS. Required if schedule_relationship=DUPLICATED, otherwise this field must not
     * be populated and will be ignored by consumers.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string trip_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTripId($var)
    {
        GPBUtil::checkString($var, True);
        $this->trip_id = $var;

        return $this;
    }

    /**
     * Service date on which the DUPLICATED trip will be run, in YYYYMMDD format. Required if
     * schedule_relationship=DUPLICATED, otherwise this field must not be populated and will be ignored by consumers.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string start_date = 2;</code>
     * @return string
     */
    public function getStartDate()
    {
        return isset($this->start_date) ? $this->start_date : '';
    }

    public function hasStartDate()
    {
        return isset($this->start_date);
    }

    public function clearStartDate()
    {
        unset($this->start_date);
    }

    /**
     * Service date on which the DUPLICATED trip will be run, in YYYYMMDD format. Required if
     * schedule_relationship=DUPLICATED, otherwise this field must not be populated and will be ignored by consumers.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string start_date = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_date = $var;

        return $this;
    }

    /**
     * Defines the departure start time of the trip when it’s duplicated. See definition of stop_times.departure_time
     * in (CSV) GTFS. Scheduled arrival and departure times for the duplicated trip are calculated based on the offset
     * between the original trip departure_time and this field. For example, if a GTFS trip has stop A with a
     * departure_time of 10:00:00 and stop B with departure_time of 10:01:00, and this field is populated with the value
     * of 10:30:00, stop B on the duplicated trip will have a scheduled departure_time of 10:31:00. Real-time prediction
     * delay values are applied to this calculated schedule time to determine the predicted time. For example, if a
     * departure delay of 30 is provided for stop B, then the predicted departure time is 10:31:30. Real-time
     * prediction time values do not have any offset applied to them and indicate the predicted time as provided.
     * For example, if a departure time representing 10:31:30 is provided for stop B, then the predicted departure time
     * is 10:31:30. This field is optional if schedule_relationship is DUPLICATED, otherwise this field must not be
     * populated and will be ignored by consumers.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string start_time = 3;</code>
     * @return string
     */
    public function getStartTime()
    {
        return isset($this->start_time) ? $this->start_time : '';
    }

    public function hasStartTime()
    {
        return isset($this->start_time);
    }

    public function clearStartTime()
    {
        unset($this->start_time);
    }

    /**
     * Defines the departure start time of the trip when it’s duplicated. See definition of stop_times.departure_time
     * in (CSV) GTFS. Scheduled arrival and departure times for the duplicated trip are calculated based on the offset
     * between the original trip departure_time and this field. For example, if a GTFS trip has stop A with a
     * departure_time of 10:00:00 and stop B with departure_time of 10:01:00, and this field is populated with the value
     * of 10:30:00, stop B on the duplicated trip will have a scheduled departure_time of 10:31:00. Real-time prediction
     * delay values are applied to this calculated schedule time to determine the predicted time. For example, if a
     * departure delay of 30 is provided for stop B, then the predicted departure time is 10:31:30. Real-time
     * prediction time values do not have any offset applied to them and indicate the predicted time as provided.
     * For example, if a departure time representing 10:31:30 is provided for stop B, then the predicted departure time
     * is 10:31:30. This field is optional if schedule_relationship is DUPLICATED, otherwise this field must not be
     * populated and will be ignored by consumers.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string start_time = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_time = $var;

        return $this;
    }

    /**
     * Specifies the identifier of the shape of the vehicle travel path when the trip shape differs from the shape specified in (CSV) GTFS
     * or to specify it in real-time when it's not provided by (CSV) GTFS, such as a vehicle that takes differing paths based on rider demand. See definition of trips.shape_id in (CSV) GTFS.
     * If a shape is neither defined in (CSV) GTFS nor in real-time, the shape is considered unknown. This field can refer to a shape defined in the (CSV) GTFS in shapes.txt or a `Shape` in the same (protobuf) real-time feed. 
     * The order of stops (stop sequences) for this trip must remain the same as (CSV) GTFS. 
     * If it refers to a `Shape` entity in the same real-time feed, the value of this field should be the one of the `shape_id` inside the entity, and _not_ the `id` of `FeedEntity`.
     * Stops that are a part of the original trip but will no longer be made, such as when a detour occurs, should be marked as schedule_relationship=SKIPPED or more details can be provided via a `TripModifications` message.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future. 
     *
     * Generated from protobuf field <code>optional string shape_id = 4;</code>
     * @return string
     */
    public function getShapeId()
    {
        return isset($this->shape_id) ? $this->shape_id : '';
    }

    public function hasShapeId()
    {
        return isset($this->shape_id);
    }

    public function clearShapeId()
    {
        unset($this->shape_id);
    }

    /**
     * Specifies the identifier of the shape of the vehicle travel path when the trip shape differs from the shape specified in (CSV) GTFS
     * or to specify it in real-time when it's not provided by (CSV) GTFS, such as a vehicle that takes differing paths based on rider demand. See definition of trips.shape_id in (CSV) GTFS.
     * If a shape is neither defined in (CSV) GTFS nor in real-time, the shape is considered unknown. This field can refer to a shape defined in the (CSV) GTFS in shapes.txt or a `Shape` in the same (protobuf) real-time feed. 
     * The order of stops (stop sequences) for this trip must remain the same as (CSV) GTFS. 
     * If it refers to a `Shape` entity in the same real-time feed, the value of this field should be the one of the `shape_id` inside the entity, and _not_ the `id` of `FeedEntity`.
     * Stops that are a part of the original trip but will no longer be made, such as when a detour occurs, should be marked as schedule_relationship=SKIPPED or more details can be provided via a `TripModifications` message.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future. 
     *
     * Generated from protobuf field <code>optional string shape_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setShapeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->shape_id = $var;

        return $this;
    }

    /**
     * Specifies the headsign for this trip when it differs from the original.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string trip_headsign = 5;</code>
     * @return string
     */
    public function getTripHeadsign()
    {
        return isset($this->trip_headsign) ? $this->trip_headsign : '';
    }

    public function hasTripHeadsign()
    {
        return isset($this->trip_headsign);
    }

    public function clearTripHeadsign()
    {
        unset($this->trip_headsign);
    }

    /**
     * Specifies the headsign for this trip when it differs from the original.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string trip_headsign = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTripHeadsign($var)
    {
        GPBUtil::checkString($var, True);
        $this->trip_headsign = $var;

        return $this;
    }

    /**
     * Specifies the name for this trip when it differs from the original.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string trip_short_name = 6;</code>
     * @return string
     */
    public function getTripShortName()
    {
        return isset($this->trip_short_name) ? $this->trip_short_name : '';
    }

    public function hasTripShortName()
    {
        return isset($this->trip_short_name);
    }

    public function clearTripShortName()
    {
        unset($this->trip_short_name);
    }

    /**
     * Specifies the name for this trip when it differs from the original.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>optional string trip_short_name = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTripShortName($var)
    {
        GPBUtil::checkString($var, True);
        $this->trip_short_name = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TripProperties::class, \Transit_realtime\TripUpdate_TripProperties::class);

