<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs-realtime-final.proto

namespace Transit_realtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Metadata about a feed, included in feed messages.
 *
 * Generated from protobuf message <code>transit_realtime.FeedHeader</code>
 */
class FeedHeader extends \Google\Protobuf\Internal\Message
{
    /**
     * Version of the feed specification.
     * The current version is 2.0.  Valid versions are "2.0", "1.0".
     *
     * Generated from protobuf field <code>optional string gtfs_realtime_version = 1;</code>
     */
    protected $gtfs_realtime_version = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.FeedHeader.Incrementality incrementality = 2;</code>
     */
    protected $incrementality = null;
    /**
     * This timestamp identifies the moment when the content of this feed has been
     * created (in server time). In POSIX time (i.e., number of seconds since
     * January 1st 1970 00:00:00 UTC).
     *
     * Generated from protobuf field <code>optional uint64 timestamp = 3;</code>
     */
    protected $timestamp = null;
    /**
     * String that matches the feed_info.feed_version from the GTFS feed that the real
     * time data is based on. Consumers can use this to identify which GTFS feed is
     * currently active or when a new one is available to download.
     *
     * Generated from protobuf field <code>optional string feed_version = 4;</code>
     */
    protected $feed_version = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $gtfs_realtime_version
     *           Version of the feed specification.
     *           The current version is 2.0.  Valid versions are "2.0", "1.0".
     *     @type int $incrementality
     *     @type int|string $timestamp
     *           This timestamp identifies the moment when the content of this feed has been
     *           created (in server time). In POSIX time (i.e., number of seconds since
     *           January 1st 1970 00:00:00 UTC).
     *     @type string $feed_version
     *           String that matches the feed_info.feed_version from the GTFS feed that the real
     *           time data is based on. Consumers can use this to identify which GTFS feed is
     *           currently active or when a new one is available to download.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GtfsRealtimeFinal::initOnce();
        parent::__construct($data);
    }

    /**
     * Version of the feed specification.
     * The current version is 2.0.  Valid versions are "2.0", "1.0".
     *
     * Generated from protobuf field <code>optional string gtfs_realtime_version = 1;</code>
     * @return string
     */
    public function getGtfsRealtimeVersion()
    {
        return isset($this->gtfs_realtime_version) ? $this->gtfs_realtime_version : '';
    }

    public function hasGtfsRealtimeVersion()
    {
        return isset($this->gtfs_realtime_version);
    }

    public function clearGtfsRealtimeVersion()
    {
        unset($this->gtfs_realtime_version);
    }

    /**
     * Version of the feed specification.
     * The current version is 2.0.  Valid versions are "2.0", "1.0".
     *
     * Generated from protobuf field <code>optional string gtfs_realtime_version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGtfsRealtimeVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->gtfs_realtime_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.FeedHeader.Incrementality incrementality = 2;</code>
     * @return int
     */
    public function getIncrementality()
    {
        return isset($this->incrementality) ? $this->incrementality : 0;
    }

    public function hasIncrementality()
    {
        return isset($this->incrementality);
    }

    public function clearIncrementality()
    {
        unset($this->incrementality);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.FeedHeader.Incrementality incrementality = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIncrementality($var)
    {
        GPBUtil::checkEnum($var, \Transit_realtime\FeedHeader\Incrementality::class);
        $this->incrementality = $var;

        return $this;
    }

    /**
     * This timestamp identifies the moment when the content of this feed has been
     * created (in server time). In POSIX time (i.e., number of seconds since
     * January 1st 1970 00:00:00 UTC).
     *
     * Generated from protobuf field <code>optional uint64 timestamp = 3;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return isset($this->timestamp) ? $this->timestamp : 0;
    }

    public function hasTimestamp()
    {
        return isset($this->timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->timestamp);
    }

    /**
     * This timestamp identifies the moment when the content of this feed has been
     * created (in server time). In POSIX time (i.e., number of seconds since
     * January 1st 1970 00:00:00 UTC).
     *
     * Generated from protobuf field <code>optional uint64 timestamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * String that matches the feed_info.feed_version from the GTFS feed that the real
     * time data is based on. Consumers can use this to identify which GTFS feed is
     * currently active or when a new one is available to download.
     *
     * Generated from protobuf field <code>optional string feed_version = 4;</code>
     * @return string
     */
    public function getFeedVersion()
    {
        return isset($this->feed_version) ? $this->feed_version : '';
    }

    public function hasFeedVersion()
    {
        return isset($this->feed_version);
    }

    public function clearFeedVersion()
    {
        unset($this->feed_version);
    }

    /**
     * String that matches the feed_info.feed_version from the GTFS feed that the real
     * time data is based on. Consumers can use this to identify which GTFS feed is
     * currently active or when a new one is available to download.
     *
     * Generated from protobuf field <code>optional string feed_version = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFeedVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->feed_version = $var;

        return $this;
    }

}

