<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs-realtime-final.proto

namespace Transit_realtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
 *
 * Generated from protobuf message <code>transit_realtime.ReplacementStop</code>
 */
class ReplacementStop extends \Google\Protobuf\Internal\Message
{
    /**
     * The difference in seconds between the arrival time at this stop and the arrival time at the reference stop. The reference stop is the stop prior to start_stop_selector. If the modification begins at the first stop of the trip, then the first stop of the trip is the reference stop.
     * This value MUST be monotonically increasing and may only be a negative number if the first stop of the original trip is the reference stop.
     *
     * Generated from protobuf field <code>optional int32 travel_time_to_stop = 1;</code>
     */
    protected $travel_time_to_stop = null;
    /**
     * The replacement stop ID which will now be visited by the trip. May refer to a new stop added using a GTFS-RT `Stop` message in the same GTFS-RT feed, or to an existing stop defined in the (CSV) GTFS feed’s `stops.txt`.
     * If it refers to a `Shape` entity in the real-time feed, the value of this field should be the one of the `stop_id` inside the entity, and _not_ the `id` of `FeedEntity`. The replacement stop MUST have `location_type=0` (routable stops).
     *
     * Generated from protobuf field <code>optional string stop_id = 2;</code>
     */
    protected $stop_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $travel_time_to_stop
     *           The difference in seconds between the arrival time at this stop and the arrival time at the reference stop. The reference stop is the stop prior to start_stop_selector. If the modification begins at the first stop of the trip, then the first stop of the trip is the reference stop.
     *           This value MUST be monotonically increasing and may only be a negative number if the first stop of the original trip is the reference stop.
     *     @type string $stop_id
     *           The replacement stop ID which will now be visited by the trip. May refer to a new stop added using a GTFS-RT `Stop` message in the same GTFS-RT feed, or to an existing stop defined in the (CSV) GTFS feed’s `stops.txt`.
     *           If it refers to a `Shape` entity in the real-time feed, the value of this field should be the one of the `stop_id` inside the entity, and _not_ the `id` of `FeedEntity`. The replacement stop MUST have `location_type=0` (routable stops).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GtfsRealtimeFinal::initOnce();
        parent::__construct($data);
    }

    /**
     * The difference in seconds between the arrival time at this stop and the arrival time at the reference stop. The reference stop is the stop prior to start_stop_selector. If the modification begins at the first stop of the trip, then the first stop of the trip is the reference stop.
     * This value MUST be monotonically increasing and may only be a negative number if the first stop of the original trip is the reference stop.
     *
     * Generated from protobuf field <code>optional int32 travel_time_to_stop = 1;</code>
     * @return int
     */
    public function getTravelTimeToStop()
    {
        return isset($this->travel_time_to_stop) ? $this->travel_time_to_stop : 0;
    }

    public function hasTravelTimeToStop()
    {
        return isset($this->travel_time_to_stop);
    }

    public function clearTravelTimeToStop()
    {
        unset($this->travel_time_to_stop);
    }

    /**
     * The difference in seconds between the arrival time at this stop and the arrival time at the reference stop. The reference stop is the stop prior to start_stop_selector. If the modification begins at the first stop of the trip, then the first stop of the trip is the reference stop.
     * This value MUST be monotonically increasing and may only be a negative number if the first stop of the original trip is the reference stop.
     *
     * Generated from protobuf field <code>optional int32 travel_time_to_stop = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTravelTimeToStop($var)
    {
        GPBUtil::checkInt32($var);
        $this->travel_time_to_stop = $var;

        return $this;
    }

    /**
     * The replacement stop ID which will now be visited by the trip. May refer to a new stop added using a GTFS-RT `Stop` message in the same GTFS-RT feed, or to an existing stop defined in the (CSV) GTFS feed’s `stops.txt`.
     * If it refers to a `Shape` entity in the real-time feed, the value of this field should be the one of the `stop_id` inside the entity, and _not_ the `id` of `FeedEntity`. The replacement stop MUST have `location_type=0` (routable stops).
     *
     * Generated from protobuf field <code>optional string stop_id = 2;</code>
     * @return string
     */
    public function getStopId()
    {
        return isset($this->stop_id) ? $this->stop_id : '';
    }

    public function hasStopId()
    {
        return isset($this->stop_id);
    }

    public function clearStopId()
    {
        unset($this->stop_id);
    }

    /**
     * The replacement stop ID which will now be visited by the trip. May refer to a new stop added using a GTFS-RT `Stop` message in the same GTFS-RT feed, or to an existing stop defined in the (CSV) GTFS feed’s `stops.txt`.
     * If it refers to a `Shape` entity in the real-time feed, the value of this field should be the one of the `stop_id` inside the entity, and _not_ the `id` of `FeedEntity`. The replacement stop MUST have `location_type=0` (routable stops).
     *
     * Generated from protobuf field <code>optional string stop_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stop_id = $var;

        return $this;
    }

}

