<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs-realtime-final.proto

namespace Transit_realtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
 * Select a stop by stop sequence or by stop_id. At least one of the two values must be provided.
 *
 * Generated from protobuf message <code>transit_realtime.StopSelector</code>
 */
class StopSelector extends \Google\Protobuf\Internal\Message
{
    /**
     * Must be the same as in stop_times.txt in the corresponding GTFS feed.
     *
     * Generated from protobuf field <code>optional uint32 stop_sequence = 1;</code>
     */
    protected $stop_sequence = null;
    /**
     * Must be the same as in stops.txt in the corresponding GTFS feed.
     *
     * Generated from protobuf field <code>optional string stop_id = 2;</code>
     */
    protected $stop_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $stop_sequence
     *           Must be the same as in stop_times.txt in the corresponding GTFS feed.
     *     @type string $stop_id
     *           Must be the same as in stops.txt in the corresponding GTFS feed.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GtfsRealtimeFinal::initOnce();
        parent::__construct($data);
    }

    /**
     * Must be the same as in stop_times.txt in the corresponding GTFS feed.
     *
     * Generated from protobuf field <code>optional uint32 stop_sequence = 1;</code>
     * @return int
     */
    public function getStopSequence()
    {
        return isset($this->stop_sequence) ? $this->stop_sequence : 0;
    }

    public function hasStopSequence()
    {
        return isset($this->stop_sequence);
    }

    public function clearStopSequence()
    {
        unset($this->stop_sequence);
    }

    /**
     * Must be the same as in stop_times.txt in the corresponding GTFS feed.
     *
     * Generated from protobuf field <code>optional uint32 stop_sequence = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStopSequence($var)
    {
        GPBUtil::checkUint32($var);
        $this->stop_sequence = $var;

        return $this;
    }

    /**
     * Must be the same as in stops.txt in the corresponding GTFS feed.
     *
     * Generated from protobuf field <code>optional string stop_id = 2;</code>
     * @return string
     */
    public function getStopId()
    {
        return isset($this->stop_id) ? $this->stop_id : '';
    }

    public function hasStopId()
    {
        return isset($this->stop_id);
    }

    public function clearStopId()
    {
        unset($this->stop_id);
    }

    /**
     * Must be the same as in stops.txt in the corresponding GTFS feed.
     *
     * Generated from protobuf field <code>optional string stop_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stop_id = $var;

        return $this;
    }

}

