<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs-realtime-final.proto

namespace Transit_realtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describes a stop which is served by trips. All fields are as described in the GTFS-Static specification.
 * NOTE: This message is still experimental, and subject to change. It may be formally adopted in the future.
 *
 * Generated from protobuf message <code>transit_realtime.Stop</code>
 */
class Stop extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string stop_id = 1;</code>
     */
    protected $stop_id = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString stop_code = 2;</code>
     */
    protected $stop_code = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString stop_name = 3;</code>
     */
    protected $stop_name = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString tts_stop_name = 4;</code>
     */
    protected $tts_stop_name = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString stop_desc = 5;</code>
     */
    protected $stop_desc = null;
    /**
     * Generated from protobuf field <code>optional float stop_lat = 6;</code>
     */
    protected $stop_lat = null;
    /**
     * Generated from protobuf field <code>optional float stop_lon = 7;</code>
     */
    protected $stop_lon = null;
    /**
     * Generated from protobuf field <code>optional string zone_id = 8;</code>
     */
    protected $zone_id = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString stop_url = 9;</code>
     */
    protected $stop_url = null;
    /**
     * Generated from protobuf field <code>optional string parent_station = 11;</code>
     */
    protected $parent_station = null;
    /**
     * Generated from protobuf field <code>optional string stop_timezone = 12;</code>
     */
    protected $stop_timezone = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.Stop.WheelchairBoarding wheelchair_boarding = 13;</code>
     */
    protected $wheelchair_boarding = null;
    /**
     * Generated from protobuf field <code>optional string level_id = 14;</code>
     */
    protected $level_id = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString platform_code = 15;</code>
     */
    protected $platform_code = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stop_id
     *     @type \Transit_realtime\TranslatedString $stop_code
     *     @type \Transit_realtime\TranslatedString $stop_name
     *     @type \Transit_realtime\TranslatedString $tts_stop_name
     *     @type \Transit_realtime\TranslatedString $stop_desc
     *     @type float $stop_lat
     *     @type float $stop_lon
     *     @type string $zone_id
     *     @type \Transit_realtime\TranslatedString $stop_url
     *     @type string $parent_station
     *     @type string $stop_timezone
     *     @type int $wheelchair_boarding
     *     @type string $level_id
     *     @type \Transit_realtime\TranslatedString $platform_code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GtfsRealtimeFinal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string stop_id = 1;</code>
     * @return string
     */
    public function getStopId()
    {
        return isset($this->stop_id) ? $this->stop_id : '';
    }

    public function hasStopId()
    {
        return isset($this->stop_id);
    }

    public function clearStopId()
    {
        unset($this->stop_id);
    }

    /**
     * Generated from protobuf field <code>optional string stop_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString stop_code = 2;</code>
     * @return \Transit_realtime\TranslatedString|null
     */
    public function getStopCode()
    {
        return $this->stop_code;
    }

    public function hasStopCode()
    {
        return isset($this->stop_code);
    }

    public function clearStopCode()
    {
        unset($this->stop_code);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString stop_code = 2;</code>
     * @param \Transit_realtime\TranslatedString $var
     * @return $this
     */
    public function setStopCode($var)
    {
        GPBUtil::checkMessage($var, \Transit_realtime\TranslatedString::class);
        $this->stop_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString stop_name = 3;</code>
     * @return \Transit_realtime\TranslatedString|null
     */
    public function getStopName()
    {
        return $this->stop_name;
    }

    public function hasStopName()
    {
        return isset($this->stop_name);
    }

    public function clearStopName()
    {
        unset($this->stop_name);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString stop_name = 3;</code>
     * @param \Transit_realtime\TranslatedString $var
     * @return $this
     */
    public function setStopName($var)
    {
        GPBUtil::checkMessage($var, \Transit_realtime\TranslatedString::class);
        $this->stop_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString tts_stop_name = 4;</code>
     * @return \Transit_realtime\TranslatedString|null
     */
    public function getTtsStopName()
    {
        return $this->tts_stop_name;
    }

    public function hasTtsStopName()
    {
        return isset($this->tts_stop_name);
    }

    public function clearTtsStopName()
    {
        unset($this->tts_stop_name);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString tts_stop_name = 4;</code>
     * @param \Transit_realtime\TranslatedString $var
     * @return $this
     */
    public function setTtsStopName($var)
    {
        GPBUtil::checkMessage($var, \Transit_realtime\TranslatedString::class);
        $this->tts_stop_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString stop_desc = 5;</code>
     * @return \Transit_realtime\TranslatedString|null
     */
    public function getStopDesc()
    {
        return $this->stop_desc;
    }

    public function hasStopDesc()
    {
        return isset($this->stop_desc);
    }

    public function clearStopDesc()
    {
        unset($this->stop_desc);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString stop_desc = 5;</code>
     * @param \Transit_realtime\TranslatedString $var
     * @return $this
     */
    public function setStopDesc($var)
    {
        GPBUtil::checkMessage($var, \Transit_realtime\TranslatedString::class);
        $this->stop_desc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional float stop_lat = 6;</code>
     * @return float
     */
    public function getStopLat()
    {
        return isset($this->stop_lat) ? $this->stop_lat : 0.0;
    }

    public function hasStopLat()
    {
        return isset($this->stop_lat);
    }

    public function clearStopLat()
    {
        unset($this->stop_lat);
    }

    /**
     * Generated from protobuf field <code>optional float stop_lat = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setStopLat($var)
    {
        GPBUtil::checkFloat($var);
        $this->stop_lat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional float stop_lon = 7;</code>
     * @return float
     */
    public function getStopLon()
    {
        return isset($this->stop_lon) ? $this->stop_lon : 0.0;
    }

    public function hasStopLon()
    {
        return isset($this->stop_lon);
    }

    public function clearStopLon()
    {
        unset($this->stop_lon);
    }

    /**
     * Generated from protobuf field <code>optional float stop_lon = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setStopLon($var)
    {
        GPBUtil::checkFloat($var);
        $this->stop_lon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string zone_id = 8;</code>
     * @return string
     */
    public function getZoneId()
    {
        return isset($this->zone_id) ? $this->zone_id : '';
    }

    public function hasZoneId()
    {
        return isset($this->zone_id);
    }

    public function clearZoneId()
    {
        unset($this->zone_id);
    }

    /**
     * Generated from protobuf field <code>optional string zone_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setZoneId($var)
    {
        GPBUtil::checkString($var, True);
        $this->zone_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString stop_url = 9;</code>
     * @return \Transit_realtime\TranslatedString|null
     */
    public function getStopUrl()
    {
        return $this->stop_url;
    }

    public function hasStopUrl()
    {
        return isset($this->stop_url);
    }

    public function clearStopUrl()
    {
        unset($this->stop_url);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString stop_url = 9;</code>
     * @param \Transit_realtime\TranslatedString $var
     * @return $this
     */
    public function setStopUrl($var)
    {
        GPBUtil::checkMessage($var, \Transit_realtime\TranslatedString::class);
        $this->stop_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string parent_station = 11;</code>
     * @return string
     */
    public function getParentStation()
    {
        return isset($this->parent_station) ? $this->parent_station : '';
    }

    public function hasParentStation()
    {
        return isset($this->parent_station);
    }

    public function clearParentStation()
    {
        unset($this->parent_station);
    }

    /**
     * Generated from protobuf field <code>optional string parent_station = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setParentStation($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent_station = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string stop_timezone = 12;</code>
     * @return string
     */
    public function getStopTimezone()
    {
        return isset($this->stop_timezone) ? $this->stop_timezone : '';
    }

    public function hasStopTimezone()
    {
        return isset($this->stop_timezone);
    }

    public function clearStopTimezone()
    {
        unset($this->stop_timezone);
    }

    /**
     * Generated from protobuf field <code>optional string stop_timezone = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setStopTimezone($var)
    {
        GPBUtil::checkString($var, True);
        $this->stop_timezone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.Stop.WheelchairBoarding wheelchair_boarding = 13;</code>
     * @return int
     */
    public function getWheelchairBoarding()
    {
        return isset($this->wheelchair_boarding) ? $this->wheelchair_boarding : 0;
    }

    public function hasWheelchairBoarding()
    {
        return isset($this->wheelchair_boarding);
    }

    public function clearWheelchairBoarding()
    {
        unset($this->wheelchair_boarding);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.Stop.WheelchairBoarding wheelchair_boarding = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setWheelchairBoarding($var)
    {
        GPBUtil::checkEnum($var, \Transit_realtime\Stop\WheelchairBoarding::class);
        $this->wheelchair_boarding = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string level_id = 14;</code>
     * @return string
     */
    public function getLevelId()
    {
        return isset($this->level_id) ? $this->level_id : '';
    }

    public function hasLevelId()
    {
        return isset($this->level_id);
    }

    public function clearLevelId()
    {
        unset($this->level_id);
    }

    /**
     * Generated from protobuf field <code>optional string level_id = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setLevelId($var)
    {
        GPBUtil::checkString($var, True);
        $this->level_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString platform_code = 15;</code>
     * @return \Transit_realtime\TranslatedString|null
     */
    public function getPlatformCode()
    {
        return $this->platform_code;
    }

    public function hasPlatformCode()
    {
        return isset($this->platform_code);
    }

    public function clearPlatformCode()
    {
        unset($this->platform_code);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TranslatedString platform_code = 15;</code>
     * @param \Transit_realtime\TranslatedString $var
     * @return $this
     */
    public function setPlatformCode($var)
    {
        GPBUtil::checkMessage($var, \Transit_realtime\TranslatedString::class);
        $this->platform_code = $var;

        return $this;
    }

}

