<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs-realtime-final.proto

namespace Transit_realtime;

if (false) {
    /**
     * This class is deprecated. Use Transit_realtime\TripUpdate\StopTimeUpdate\StopTimeProperties\DropOffPickupType instead.
     * @deprecated
     */
    class TripUpdate_StopTimeUpdate_StopTimeProperties_DropOffPickupType {}
}
class_exists(TripUpdate\StopTimeUpdate\StopTimeProperties\DropOffPickupType::class);
@trigger_error('Transit_realtime\TripUpdate_StopTimeUpdate_StopTimeProperties_DropOffPickupType is deprecated and will be removed in the next major release. Use Transit_realtime\TripUpdate\StopTimeUpdate\StopTimeProperties\DropOffPickupType instead', E_USER_DEPRECATED);

