<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs-realtime-final.proto

namespace Transit_realtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Identification information for the vehicle performing the trip.
 *
 * Generated from protobuf message <code>transit_realtime.VehicleDescriptor</code>
 */
class VehicleDescriptor extends \Google\Protobuf\Internal\Message
{
    /**
     * Internal system identification of the vehicle. Should be unique per
     * vehicle, and can be used for tracking the vehicle as it proceeds through
     * the system.
     *
     * Generated from protobuf field <code>optional string id = 1;</code>
     */
    protected $id = null;
    /**
     * User visible label, i.e., something that must be shown to the passenger to
     * help identify the correct vehicle.
     *
     * Generated from protobuf field <code>optional string label = 2;</code>
     */
    protected $label = null;
    /**
     * The license plate of the vehicle.
     *
     * Generated from protobuf field <code>optional string license_plate = 3;</code>
     */
    protected $license_plate = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.VehicleDescriptor.WheelchairAccessible wheelchair_accessible = 4;</code>
     */
    protected $wheelchair_accessible = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Internal system identification of the vehicle. Should be unique per
     *           vehicle, and can be used for tracking the vehicle as it proceeds through
     *           the system.
     *     @type string $label
     *           User visible label, i.e., something that must be shown to the passenger to
     *           help identify the correct vehicle.
     *     @type string $license_plate
     *           The license plate of the vehicle.
     *     @type int $wheelchair_accessible
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GtfsRealtimeFinal::initOnce();
        parent::__construct($data);
    }

    /**
     * Internal system identification of the vehicle. Should be unique per
     * vehicle, and can be used for tracking the vehicle as it proceeds through
     * the system.
     *
     * Generated from protobuf field <code>optional string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : '';
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Internal system identification of the vehicle. Should be unique per
     * vehicle, and can be used for tracking the vehicle as it proceeds through
     * the system.
     *
     * Generated from protobuf field <code>optional string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * User visible label, i.e., something that must be shown to the passenger to
     * help identify the correct vehicle.
     *
     * Generated from protobuf field <code>optional string label = 2;</code>
     * @return string
     */
    public function getLabel()
    {
        return isset($this->label) ? $this->label : '';
    }

    public function hasLabel()
    {
        return isset($this->label);
    }

    public function clearLabel()
    {
        unset($this->label);
    }

    /**
     * User visible label, i.e., something that must be shown to the passenger to
     * help identify the correct vehicle.
     *
     * Generated from protobuf field <code>optional string label = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * The license plate of the vehicle.
     *
     * Generated from protobuf field <code>optional string license_plate = 3;</code>
     * @return string
     */
    public function getLicensePlate()
    {
        return isset($this->license_plate) ? $this->license_plate : '';
    }

    public function hasLicensePlate()
    {
        return isset($this->license_plate);
    }

    public function clearLicensePlate()
    {
        unset($this->license_plate);
    }

    /**
     * The license plate of the vehicle.
     *
     * Generated from protobuf field <code>optional string license_plate = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLicensePlate($var)
    {
        GPBUtil::checkString($var, True);
        $this->license_plate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.VehicleDescriptor.WheelchairAccessible wheelchair_accessible = 4;</code>
     * @return int
     */
    public function getWheelchairAccessible()
    {
        return isset($this->wheelchair_accessible) ? $this->wheelchair_accessible : 0;
    }

    public function hasWheelchairAccessible()
    {
        return isset($this->wheelchair_accessible);
    }

    public function clearWheelchairAccessible()
    {
        unset($this->wheelchair_accessible);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.VehicleDescriptor.WheelchairAccessible wheelchair_accessible = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setWheelchairAccessible($var)
    {
        GPBUtil::checkEnum($var, \Transit_realtime\VehicleDescriptor\WheelchairAccessible::class);
        $this->wheelchair_accessible = $var;

        return $this;
    }

}

